### ISSUE TITLE
Exception: No BOUND object in scene

### ISSUE THREAD

**Issue by takanuva15** [Dummiesman/BNDImportExport#4]
I created a new file and added a cube. I triangulated the cube and then selected it and tried to export it as BND but it failed with the exception:

`Exception: No BOUND object in scene.`

I'm very new to `.bnd` files so I'm confused what I might be doing wrong? How do I convert the cube to a BOUND object?

**Comment by Dummiesman** [comment]
The script looks for an object named 'BOUND'. This is basically keeping old tradition of how ZModeler would export a BND if a BOUND object was present.

**Comment by takanuva15** [comment]
Ah ok got it. (Haven't used ZModeler before lol)
